/** Optimized WebP paths (generated by `npm run optimize-images`) + original fallbacks. */
export type SiteImage = {
  fallback: string;
  webp: string;
  alt: string;
};

export const heroSlides: SiteImage[] = [
  {
    fallback: "/images/banner.jpeg",
    webp: "/optimized/banner.webp",
    alt: "Facility management banner",
  },
  {
    fallback: "/images/banner2.jpeg",
    webp: "/optimized/banner2.webp",
    alt: "Facility services banner",
  },
  {
    fallback: "/images/herobg.png",
    webp: "/optimized/herobg.webp",
    alt: "Saryab Technicals hero background",
  },
];

export const aboutImage: SiteImage = {
  fallback: "/images/about2.png",
  webp: "/optimized/about2.webp",
  alt: "Saryab Technicals facility team",
};

export const ctaImage: SiteImage = {
  fallback: "/images/cta.png",
  webp: "/optimized/cta.webp",
  alt: "Contact CTA",
};

export const projectImages = {
  office: {
    fallback: "/images/projects/office.png",
    webp: "/optimized/projects/office.webp",
    alt: "Office Fitout Project",
  },
  hvac: {
    fallback: "/images/projects/hvac.png",
    webp: "/optimized/projects/hvac.webp",
    alt: "Commercial HVAC Upgrade",
  },
  cleaning: {
    fallback: "/images/projects/cleaning.png",
    webp: "/optimized/projects/cleaning.webp",
    alt: "Hotel Cleaning Contract",
  },
  security: {
    fallback: "/images/projects/security.png",
    webp: "/optimized/projects/security.webp",
    alt: "Security System Installation",
  },
  pool: {
    fallback: "/images/projects/swimming-pool.png",
    webp: "/optimized/projects/swimming-pool.webp",
    alt: "Pool Maintenance Program",
  },
  maintenance: {
    fallback: "/images/projects/maintance.png",
    webp: "/optimized/projects/maintance.webp",
    alt: "Building Maintenance Contract",
  },
} as const satisfies Record<string, SiteImage>;
